# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Run tests and checks

on: pull_request

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.12"]

    permissions:
      pull-requests: write
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Python, Poetry and Dependencies
      uses: actions/setup-python@v5
      with:
          python-version: ${{matrix.python-version}}
    - run: poetry install --with dev
    - run: echo "$(poetry env info --path)/bin" >> $GITHUB_PATH

    - name: Lint with Ruff
      run: |
        ruff check --output-format=github .
    - name: Install ReX
      run: |
        poetry install 
    - name: Test with pytest
      run: |
        pytest --junitxml=pytest.xml --cov-report=xml:coverage.xml --cov=rex_xai tests/
    - name: Pytest coverage comment
      uses: MishaKav/pytest-coverage-comment@v1.1.52
      with:
        pytest-xml-coverage-path: ./coverage.xml
    - name: Type checking with Pyright
      uses:  jordemort/action-pyright@v1
      with:
        workdir: "./rex_xai"
        github_token: ${{ secrets.GITHUB_TOKEN }} # You need this
        reporter: github-pr-check 

