# This workflow will install ReX and run tests, using the highest and lowest Python versions we support
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Install and run tests 

on: 
  workflow_call:
  pull_request:

jobs:
  test:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.13"]

    permissions:
      pull-requests: write
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install poetry
      run: pipx install poetry
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
          python-version: ${{matrix.python-version}}
          cache: poetry
    
    - name: Install project and dependencies 
      run: poetry install --with dev
    
    - name: Update PATH
      run: echo "$(poetry env info --path)/bin" >> $GITHUB_PATH

    - name: Cache model files for testing
      uses: actions/cache@v3
      env:
        cache-name: cache-model-files
      with:
        path: ~/.cache/cached_path
        key: ${{ runner.os }}-test-${{ env.cache-name }}-${{ hashFiles('tests/conftest.py') }}

    - name: Test with pytest
      run: |
        pytest --junitxml=pytest.xml --cov-report=xml:coverage.xml --cov=rex_xai tests/
    
    - name: Pytest coverage comment
      uses: MishaKav/pytest-coverage-comment@v1.1.52
      if: ${{ !github.event.pull_request.head.repo.fork }}
      with:
        pytest-xml-coverage-path: ./coverage.xml


